#!/usr/bin/env python3
"""Apply German->English translations to .po file."""
import re

TRANSLATIONS = [
    (r'msgstr ""\n"GutenBlock Pro lädt CSS und JS.*?verwendet werden\."', 
     'msgstr "GutenBlock Pro loads CSS and JS only for patterns used on the current page."'),
    ('msgstr "Die Erkennung basiert auf der CSS-Klasse:"', 'msgstr "Detection is based on the CSS class:"'),
    ('msgstr "Pfade"', 'msgstr "Paths"'),
    ('msgstr "Plugin-Verzeichnis"', 'msgstr "Plugin directory"'),
    ('msgstr "Patterns-Verzeichnis"', 'msgstr "Patterns directory"'),
    ('msgstr "Bilder erfolgreich aktualisiert"', 'msgstr "Images updated successfully"'),
    ('msgstr "Keine picsum.photos Bilder gefunden"', 'msgstr "No picsum.photos images found"'),
    ('msgstr "Prompt ist erforderlich"', 'msgstr "Prompt is required"'),
    ('msgstr ""\n"Monatliches Token-Limit erreicht.*?Generierung\."', 
     'msgstr "Monthly token limit reached. Upgrade to Pro for unlimited generation."'),
    ('msgstr "API-Key nicht konfiguriert"', 'msgstr "API key not configured"'),
    ('msgstr "Schreibe einen passenden Text für das Element „%s\"."', 'msgstr "Write suitable text for the element \"%s\"."'),
    ('msgstr "Fehler bei der AI-Generierung: "', 'msgstr "Error during AI generation: "'),
    ('msgstr "Keine Content-Felder angegeben"', 'msgstr "No content fields specified"'),
    ('msgstr "Ungültige JSON-Response von der API. Response: "', 'msgstr "Invalid JSON response from API. Response: "'),
    ('msgstr "Rate-Limit erreicht. Bitte warte einen Moment."', 'msgstr "Rate limit reached. Please wait a moment."'),
    ('msgstr "AI-Generierung fehlgeschlagen"', 'msgstr "AI generation failed"'),
    ('msgstr "Kein Text zum Übersetzen"', 'msgstr "No text to translate"'),
    ('msgstr "Token-Limit erreicht"', 'msgstr "Token limit reached"'),
    ('msgstr "KI-Einstellungen"', 'msgstr "AI Settings"'),
    ('msgstr "Aktiviere..."', 'msgstr "Activating..."'),
    ('msgstr "Deaktiviere..."', 'msgstr "Deactivating..."'),
    ('msgstr "Lade Prompts..."', 'msgstr "Loading prompts..."'),
    ('msgstr "GutenBlock Pro - KI-Einstellungen"', 'msgstr "GutenBlock Pro - AI Settings"'),
    ('msgstr "Lizenz"', 'msgstr "License"'),
    ('msgstr "Pro-Lizenz aktiv"', 'msgstr "Pro license active"'),
    ('msgstr "Lizenz deaktivieren"', 'msgstr "Deactivate license"'),
    ('msgstr "Kostenlose Version"', 'msgstr "Free version"'),
    ('msgstr "Lizenz aktivieren"', 'msgstr "Activate license"'),
    ('msgstr "Noch keine Lizenz? %s"', 'msgstr "No license yet? %s"'),
    ('msgstr "Jetzt kaufen"', 'msgstr "Buy now"'),
    ('msgstr "1 Mio. AI-Tokens monatlich"', 'msgstr "1M AI tokens monthly"'),
    ('msgstr "Alle Premium-Patterns freigeschalten"', 'msgstr "All premium patterns unlocked"'),
    ('msgstr "Einmalig zahlen, lebenslang nutzen"', 'msgstr "Pay once, use forever"'),
    ('msgstr "Token-Verbrauch"', 'msgstr "Token usage"'),
    ('msgstr "Unbegrenzte Tokens (Pro)"', 'msgstr "Unlimited tokens (Pro)"'),
    ('msgstr "Tokens"', 'msgstr "Tokens"'),
    ('msgstr "Verbleibend: %1$s Tokens. Reset: %2$s"', 'msgstr "Remaining: %1$s tokens. Reset: %2$s"'),
    ('msgstr "KI-Prompts"', 'msgstr "AI Prompts"'),
    ('msgstr ""\n"Definiere den Stil und Kontext.*?kombiniert verwendet\."',
     'msgstr "Define style and context for all AI-generated texts. These prompts are combined for each generation."'),
    ('msgstr "Stil"', 'msgstr "Style"'),
    ('msgstr "Definiere den Schreibstil und technische Vorgaben für die Texte."', 
     'msgstr "Define writing style and technical guidelines for the texts."'),
    ('msgstr "Kontext"', 'msgstr "Context"'),
    ('msgstr ""\n"z.B. Ich bin ein Marketing-Berater.*?Transformation..."',
     'msgstr "e.g. I am a marketing consultant helping companies with digital transformation..."'),
    ('msgstr ""\n"Beschreibe wer du bist.*? kombiniert\."',
     'msgstr "Describe who you are and what you do. This is combined with the style."'),
    ('msgstr "Bild-API Anbieter"', 'msgstr "Image API provider"'),
    ('msgstr "Pexels"', 'msgstr "Pexels"'),
    ('msgstr "Unsplash"', 'msgstr "Unsplash"'),
    ('msgstr ""\n"Wähle den API-Anbieter.*?verwendet\."',
     'msgstr "Select API provider for image search. Without API key, picsum.photos is used."'),
    ('msgstr "Pexels API Key"', 'msgstr "Pexels API Key"'),
    ('msgstr "Unsplash API Key"', 'msgstr "Unsplash API Key"'),
    ('msgstr "Einstellungen speichern"', 'msgstr "Save settings"'),
    ('msgstr "Block-Prompts"', 'msgstr "Block Prompts"'),
    ('msgstr "Prompts mit API synchronisieren"', 'msgstr "Synchronize prompts with API"'),
    ('msgstr ""\n"Diese Prompts werden.*?überschreiben die API-Prompts\."',
     'msgstr "These prompts are synced with gutenblock.com API and define which text is generated for which block element. Custom prompts override API prompts."'),
    ('msgstr "Block-ID"', 'msgstr "Block ID"'),
    ('msgstr "Prompt (API)"', 'msgstr "Prompt (API)"'),
    ('msgstr "Custom Prompt"', 'msgstr "Custom Prompt"'),
    ('msgstr "Optional: Eigener Prompt (überschreibt API-Prompt)"', 'msgstr "Optional: Custom prompt (overrides API prompt)"'),
    ('msgstr "Custom Prompts speichern"', 'msgstr "Save custom prompts"'),
    ('msgstr ""\n"Keine Prompts geladen.*?zu laden\."',
     'msgstr "No prompts loaded. Click \"Update\" to load prompts from gutenblock.com."'),
    ('msgstr "Keine Berechtigung"', 'msgstr "No permission"'),
    ('msgstr "Bitte Lizenzschlüssel eingeben"', 'msgstr "Please enter license key"'),
    ('msgstr "Prompts erfolgreich aktualisiert"', 'msgstr "Prompts updated successfully"'),
    ('msgstr "Keine Prompts gefunden. Prüfe die Verbindung zu gutenblock.com"', 
     'msgstr "No prompts found. Check connection to gutenblock.com"'),
    ('msgstr "Custom Prompts erfolgreich gespeichert"', 'msgstr "Custom prompts saved successfully"'),
    ('msgstr "Zeigt Checkmarks (✓) statt Bullets für alle Listenelemente"', 
     'msgstr "Shows checkmarks (✓) instead of bullets for all list items"'),
    ('msgstr "Welle"', 'msgstr "Wave"'),
    ('msgstr "Diagonale"', 'msgstr "Diagonal"'),
    ('msgstr "Bogen"', 'msgstr "Arch"'),
    ('msgstr "Spitze"', 'msgstr "Point"'),
    ('msgstr "Zickzack"', 'msgstr "Zigzag"'),
    ('msgstr "Aktiviere oder deaktiviere optionale Funktionen von GutenBlock Pro."',
     'msgstr "Enable or disable optional GutenBlock Pro features."'),
    ('msgstr "Lizenz erfolgreich aktiviert!"', 'msgstr "License activated successfully!"'),
    ('msgstr "Aktivierung fehlgeschlagen"', 'msgstr "Activation failed"'),
    ('msgstr "Lizenz deaktiviert"', 'msgstr "License deactivated"'),
    ('msgstr "Als GB Pro Pattern speichern"', 'msgstr "Save as GB Pro Pattern"'),
    ('msgstr "GutenBlock Pro Pattern erstellen"', 'msgstr "Create GutenBlock Pro Pattern"'),
    ('msgstr "Pattern Name"', 'msgstr "Pattern Name"'),
    ('msgstr "Mein neues Pattern"', 'msgstr "My new pattern"'),
    ('msgstr "Slug"', 'msgstr "Slug"'),
    ('msgstr "Wird automatisch generiert"', 'msgstr "Generated automatically"'),
    ('msgstr "Beschreibung"', 'msgstr "Description"'),
    ('msgstr "Kurze Beschreibung des Patterns"', 'msgstr "Short pattern description"'),
    ('msgstr "Keywords"', 'msgstr "Keywords"'),
    ('msgstr "hero, cta, button (kommagetrennt)"', 'msgstr "hero, cta, button (comma-separated)"'),
    ('msgstr "Sprache"', 'msgstr "Language"'),
    ('msgstr "Für welche Sprache ist dieser Content?"', 'msgstr "For which language is this content?"'),
    ('msgstr "Default (Fallback)"', 'msgstr "Default (Fallback)"'),
    ('msgstr "Typ"', 'msgstr "Type"'),
    ('msgstr "Section"', 'msgstr "Section"'),
    ('msgstr "Seite"', 'msgstr "Page"'),
    ('msgstr "Gruppe"', 'msgstr "Group"'),
    ('msgstr "Lokale Bilder ersetzen"', 'msgstr "Replace local images"'),
    ('msgstr "Ersetzt Bilder aus dem Uploads-Ordner durch Placeholder (picsum.photos)"',
     'msgstr "Replaces upload folder images with placeholders (picsum.photos)"'),
    ('msgstr "Pattern erstellen"', 'msgstr "Create pattern"'),
    ('msgstr "Content aktualisieren"', 'msgstr "Update content"'),
    ('msgstr "Bestehendes Pattern aktualisieren"', 'msgstr "Update existing pattern"'),
    ('msgstr "Nur content.html wird überschrieben. CSS und JS bleiben erhalten."',
     'msgstr "Only content.html is overwritten. CSS and JS remain."'),
    ('msgstr "Pattern existiert bereits. Content wird aktualisiert."', 'msgstr "Pattern already exists. Content will be updated."'),
    ('msgstr "Abbrechen"', 'msgstr "Cancel"'),
    ('msgstr "Erstelle Pattern..."', 'msgstr "Creating pattern..."'),
    ('msgstr "Pattern erfolgreich erstellt!"', 'msgstr "Pattern created successfully!"'),
    ('msgstr "Fehler beim Erstellen des Patterns"', 'msgstr "Error creating pattern"'),
    ('msgstr "Bitte wähle mindestens einen Block aus."', 'msgstr "Please select at least one block."'),
    ('msgstr "Bitte gib einen Namen ein."', 'msgstr "Please enter a name."'),
    ('msgstr "KI Übersetzungen"', 'msgstr "AI Translations"'),
    ('msgstr ""\n"Aktiviere die Sprachen.*?in der Sidebar\."',
     'msgstr "Enable languages for editor translation. Each enabled language appears as a button in the sidebar."'),
    ('msgstr "Fehler bei der Generierung"', 'msgstr "Error during generation"'),
    ('msgstr "Mindestens 3 Zeichen Text erforderlich"', 'msgstr "At least 3 characters of text required"'),
    ('msgstr "Fehler bei der Übersetzung"', 'msgstr "Error during translation"'),
    ('msgstr "GutenBlock AI"', 'msgstr "GutenBlock AI"'),
    ('msgstr "Content-Feld"', 'msgstr "Content field"'),
    ('msgstr "Prompt (aus Content-Feld)"', 'msgstr "Prompt (from content field)"'),
    ('msgstr "Eigener Prompt"', 'msgstr "Custom prompt"'),
    ('msgstr "Wähle ein Content-Feld oder schreibe einen eigenen Prompt..."', 
     'msgstr "Select a content field or write a custom prompt..."'),
    ('msgstr ""\n"Der Prompt wird aus dem Content-Feld geladen.*?anpassen\."',
     'msgstr "The prompt is loaded from the content field. You can adjust it here temporarily."'),
    ('msgstr "Generieren"', 'msgstr "Generate"'),
    ('msgstr "Variante"', 'msgstr "Variant"'),
    ('msgstr "Neu"', 'msgstr "New"'),
    ('msgstr "Keine übersetzbaren Textblöcke gefunden."', 'msgstr "No translatable text blocks found."'),
    ('msgstr "Übersetzen"', 'msgstr "Translate"'),
    ('msgstr "übersetzt…"', 'msgstr "translated…"'),
    ('msgstr "Ganze Seite übersetzen"', 'msgstr "Translate entire page"'),
    ('msgstr ""\n"Alle Textblöcke auf dieser Seite werden übersetzt.*?dauern\."',
     'msgstr "All text blocks on this page will be translated. This may take a moment."'),
    ('msgstr ""\n"Die Übersetzung aller Textblöcke.*?verbrauchen\."',
     'msgstr "Translating all text blocks on this page may consume many tokens."'),
    ('msgstr "Token-Limit erhöhen"', 'msgstr "Increase token limit"'),
    ('msgstr "Trotzdem übersetzen"', 'msgstr "Translate anyway"'),
    ('msgstr "Keine Content-Felder in dieser Gruppe gefunden."', 'msgstr "No content fields found in this group."'),
    ('msgstr "GutenBlock AI - Gruppe"', 'msgstr "GutenBlock AI - Group"'),
    ('msgstr "Gefundene Content-Felder:"', 'msgstr "Found content fields:"'),
    ('msgstr "Keine Content-Felder mit metadata.name in dieser Gruppe gefunden."',
     'msgstr "No content fields with metadata.name found in this group."'),
    ('msgstr "Gruppen-Prompt"', 'msgstr "Group prompt"'),
    ('msgstr "Beschreibe, was für alle Content-Felder generiert werden soll..."',
     'msgstr "Describe what should be generated for all content fields..."'),
    ('msgstr "Dieser Prompt wird für alle Content-Felder in der Gruppe verwendet."',
     'msgstr "This prompt is used for all content fields in the group."'),
    ('msgstr "Alle Felder generieren"', 'msgstr "Generate all fields"'),
    ('msgstr ""\n"Hinweis: Füge Blöcke mit metadata.name.*?sehen\."',
     'msgstr "Note: Add blocks with metadata.name to this group to see them here."'),
    ('msgstr "🔒 Pro Plus erforderlich"', 'msgstr "🔒 Pro Plus required"'),
    ('msgstr ""\n"Dieses Pattern kann als Vorschau eingefügt werden.*?bearbeitbar\."',
     'msgstr "This pattern can be inserted as preview but is only editable with GutenBlock Pro Plus."'),
    ('msgstr "Jetzt upgraden"', 'msgstr "Upgrade now"'),
    ('msgstr "SVG konnte nicht geladen werden."', 'msgstr "SVG could not be loaded."'),
    ('msgstr "Fehler beim Laden des SVG."', 'msgstr "Error loading SVG."'),
    ('msgstr "SVG aus der Mediabibliothek wählen oder neu hochladen. Nur SVG-Dateien."',
     'msgstr "Select SVG from media library or upload new. SVG files only."'),
    ('msgstr "Bitte eine SVG-Datei wählen."', 'msgstr "Please select an SVG file."'),
    ('msgstr "Laden…"', 'msgstr "Loading…"'),
    ('msgstr "SVG hochladen oder auswählen"', 'msgstr "Upload or select SVG"'),
    ('msgstr "Outlined"', 'msgstr "Outlined"'),
    ('msgstr "Rounded"', 'msgstr "Rounded"'),
    ('msgstr "Sharp"', 'msgstr "Sharp"'),
    ('msgstr "Icon-Einstellungen"', 'msgstr "Icon settings"'),
    ('msgstr "Stärke"', 'msgstr "Weight"'),
    ('msgstr "Größe (px)"', 'msgstr "Size (px)"'),
    ('msgstr "Farbe"', 'msgstr "Color"'),
    ('msgstr "Icon wechseln"', 'msgstr "Change icon"'),
    ('msgstr "Icon wählen"', 'msgstr "Select icon"'),
    ('msgstr "Icon konnte nicht geladen werden."', 'msgstr "Icon could not be loaded."'),
    ('msgstr "Erneut laden"', 'msgstr "Retry"'),
    ('msgstr "Icon auswählen"', 'msgstr "Select icon"'),
    ('msgstr "Schließen"', 'msgstr "Close"'),
    ('msgstr "Material Symbols"', 'msgstr "Material Symbols"'),
    ('msgstr "Eigene SVG"', 'msgstr "Custom SVG"'),
    ('msgstr "Icon suchen (z.B. home, arrow)…"', 'msgstr "Search icon (e.g. home, arrow)…"'),
    ('msgstr "Icons"', 'msgstr "Icons"'),
    ('msgstr "Keine Icons gefunden."', 'msgstr "No icons found."'),
    ('msgstr "Mindestens 2 Zeichen eingeben."', 'msgstr "Enter at least 2 characters."'),
    ('msgstr "Material Icon"', 'msgstr "Material Icon"'),
    ('msgstr "Google Material Symbol als Inline-SVG mit Suche, Größe und Farbe."',
     'msgstr "Google Material Symbol as inline SVG with search, size and color."'),
    ('msgstr "Icon"', 'msgstr "Icon"'),
    ('msgstr "SVG"', 'msgstr "SVG"'),
    ('msgstr "Material"', 'msgstr "Material"'),
]

def main():
    path = 'languages/gutenblock-pro-en_US.po'
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for old, new in TRANSLATIONS:
        if 'msgstr ""' in old and '\\n' in old:
            content = re.sub(old, new, content, flags=re.DOTALL)
        else:
            content = content.replace(old, new)
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print('Done')

if __name__ == '__main__':
    main()
